
package com.kunai.keyvault.crypto.voltage.vibesimple;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VibeSimple", targetNamespace = "http://voltage.com/vibesimple", wsdlLocation = "https://10.111.109.30/vibesimple/services/VibeSimpleSOAP?wsdl")
public class VibeSimple_Service
    extends Service
{

    private final static URL VIBESIMPLE_WSDL_LOCATION;
    private final static WebServiceException VIBESIMPLE_EXCEPTION;
    private final static QName VIBESIMPLE_QNAME = new QName("http://voltage.com/vibesimple", "VibeSimple");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://10.111.109.30/vibesimple/services/VibeSimpleSOAP?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VIBESIMPLE_WSDL_LOCATION = url;
        VIBESIMPLE_EXCEPTION = e;
    }

    public VibeSimple_Service() {
        super(__getWsdlLocation(), VIBESIMPLE_QNAME);
    }

    public VibeSimple_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), VIBESIMPLE_QNAME, features);
    }

    public VibeSimple_Service(URL wsdlLocation) {
        super(wsdlLocation, VIBESIMPLE_QNAME);
    }

    public VibeSimple_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VIBESIMPLE_QNAME, features);
    }

    public VibeSimple_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VibeSimple_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VibeSimple
     */
    @WebEndpoint(name = "VibeSimpleSOAP")
    public VibeSimple getVibeSimpleSOAP() {
        return super.getPort(new QName("http://voltage.com/vibesimple", "VibeSimpleSOAP"), VibeSimple.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VibeSimple
     */
    @WebEndpoint(name = "VibeSimpleSOAP")
    public VibeSimple getVibeSimpleSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://voltage.com/vibesimple", "VibeSimpleSOAP"), VibeSimple.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VIBESIMPLE_EXCEPTION!= null) {
            throw VIBESIMPLE_EXCEPTION;
        }
        return VIBESIMPLE_WSDL_LOCATION;
    }

}
