
package com.kunai.keyvault.crypto.voltage.vibesimple;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VibeSimple", targetNamespace = "http://voltage.com/vibesimple")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VibeSimple {


    /**
     * 
     * @param encryptIdentity a List of String
     * @param signAuthInfo a String representing the auth info.
     * @param signAuthMethod an AuthMethod object
     * @param signIdentity a String representing the sign identity.
     * @param outputFormat a DataFormat object
     * @param dataIn a byte[]
     * @return byte[]
     * @throws FaultResponse
     */
    @WebMethod(operationName = "ProtectData", action = "http://voltage.com/vibesimple/ProtectData")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "ProtectData", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectData")
    @ResponseWrapper(localName = "ProtectDataResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectDataResponse")
    public byte[] protectData(
            @WebParam(name = "dataIn", targetNamespace = "")
            byte[] dataIn,
            @WebParam(name = "encryptIdentity", targetNamespace = "")
            List<String> encryptIdentity,
            @WebParam(name = "signIdentity", targetNamespace = "")
            String signIdentity,
            @WebParam(name = "signAuthMethod", targetNamespace = "")
            AuthMethod signAuthMethod,
            @WebParam(name = "signAuthInfo", targetNamespace = "")
            String signAuthInfo,
            @WebParam(name = "outputFormat", targetNamespace = "")
            DataFormat outputFormat)
        throws FaultResponse
    ;

    /**
     * 
     * @param encryptIdentity
     * @param authenticationIdentity
     * @param authMethod
     * @param dataIn
     * @param authInfo
     * @return byte[]
     * @throws FaultResponse
     */
    @WebMethod(operationName = "ProtectUnsignedData", action = "http://voltage.com/vibesimple/ProtectUnsignedData")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "ProtectUnsignedData", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectUnsignedData")
    @ResponseWrapper(localName = "ProtectUnsignedDataResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectUnsignedDataResponse")
    public byte[] protectUnsignedData(
            @WebParam(name = "dataIn", targetNamespace = "")
            byte[] dataIn,
            @WebParam(name = "encryptIdentity", targetNamespace = "")
            List<String> encryptIdentity,
            @WebParam(name = "authenticationIdentity", targetNamespace = "")
            String authenticationIdentity,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo)
        throws FaultResponse
    ;

    /**
     * 
     * @param dataOut
     * @param decryptAuthMethod
     * @param decryptIdentity
     * @param signIdentity
     * @param dataIn
     * @param decryptAuthInfo
     * @throws FaultResponse
     */
    @WebMethod(operationName = "AccessData", action = "http://voltage.com/vibesimple/AccessData")
    @RequestWrapper(localName = "AccessData", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessData")
    @ResponseWrapper(localName = "AccessDataResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessDataResponse")
    public void accessData(
            @WebParam(name = "dataIn", targetNamespace = "")
            byte[] dataIn,
            @WebParam(name = "decryptIdentity", targetNamespace = "")
            String decryptIdentity,
            @WebParam(name = "decryptAuthMethod", targetNamespace = "")
            AuthMethod decryptAuthMethod,
            @WebParam(name = "decryptAuthInfo", targetNamespace = "")
            String decryptAuthInfo,
            @WebParam(name = "dataOut", targetNamespace = "", mode = WebParam.Mode.OUT)
            Holder<byte[]> dataOut,
            @WebParam(name = "signIdentity", targetNamespace = "", mode = WebParam.Mode.OUT)
            Holder<String> signIdentity)
        throws FaultResponse
    ;

    /**
     * 
     * @param dataIn
     * @return java.util.List{@literal <}java.lang.String{@literal >}
     * @throws FaultResponse
     */
    @WebMethod(operationName = "GetAccessList", action = "http://voltage.com/vibesimple/GetAccessList")
    @WebResult(name = "identity", targetNamespace = "")
    @RequestWrapper(localName = "GetAccessList", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.GetAccessList")
    @ResponseWrapper(localName = "GetAccessListResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.GetAccessListResponse")
    public List<String> getAccessList(
            @WebParam(name = "dataIn", targetNamespace = "")
            byte[] dataIn)
        throws FaultResponse
    ;

    /**
     * 
     * @param creditCardNumber
     * @param identity
     * @param tweak
     * @param authMethod
     * @param authInfo
     * @return java.lang.String
     * @throws FaultResponse
     */
    @WebMethod(operationName = "ProtectCreditCardNumber", action = "http://voltage.com/vibesimple/ProtectCreditCardNumber")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "ProtectCreditCardNumber", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectCreditCardNumber")
    @ResponseWrapper(localName = "ProtectCreditCardNumberResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectCreditCardNumberResponse")
    public String protectCreditCardNumber(
            @WebParam(name = "creditCardNumber", targetNamespace = "")
            String creditCardNumber,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "tweak", targetNamespace = "")
            String tweak,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo)
        throws FaultResponse
    ;

    /**
     * 
     * @param creditCardNumber
     * @param identity
     * @param tweak
     * @param masked
     * @param authMethod
     * @param authInfo
     * @return java.lang.String
     * @throws FaultResponse
     */
    @WebMethod(operationName = "AccessCreditCardNumber", action = "http://voltage.com/vibesimple/AccessCreditCardNumber")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "AccessCreditCardNumber", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessCreditCardNumber")
    @ResponseWrapper(localName = "AccessCreditCardNumberResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessCreditCardNumberResponse")
    public String accessCreditCardNumber(
            @WebParam(name = "creditCardNumber", targetNamespace = "")
            String creditCardNumber,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "tweak", targetNamespace = "")
            String tweak,
            @WebParam(name = "masked", targetNamespace = "")
            Boolean masked,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo)
        throws FaultResponse
    ;

    /**
     * 
     * @param socialSecurityNumber
     * @param identity
     * @param tweak
     * @param authMethod
     * @param authInfo
     * @return java.lang.String
     * @throws FaultResponse
     */
    @WebMethod(operationName = "ProtectSocialSecurityNumber", action = "http://voltage.com/vibesimple/ProtectSocialSecurityNumber")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "ProtectSocialSecurityNumber", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectSocialSecurityNumber")
    @ResponseWrapper(localName = "ProtectSocialSecurityNumberResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectSocialSecurityNumberResponse")
    public String protectSocialSecurityNumber(
            @WebParam(name = "socialSecurityNumber", targetNamespace = "")
            String socialSecurityNumber,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "tweak", targetNamespace = "")
            String tweak,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo)
        throws FaultResponse
    ;

    /**
     * 
     * @param socialSecurityNumber
     * @param identity
     * @param tweak
     * @param masked
     * @param authMethod
     * @param authInfo
     * @return
     *     returns java.lang.String
     * @throws FaultResponse
     */
    @WebMethod(operationName = "AccessSocialSecurityNumber", action = "http://voltage.com/vibesimple/AccessSocialSecurityNumber")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "AccessSocialSecurityNumber", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessSocialSecurityNumber")
    @ResponseWrapper(localName = "AccessSocialSecurityNumberResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessSocialSecurityNumberResponse")
    public String accessSocialSecurityNumber(
            @WebParam(name = "socialSecurityNumber", targetNamespace = "")
            String socialSecurityNumber,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "tweak", targetNamespace = "")
            String tweak,
            @WebParam(name = "masked", targetNamespace = "")
            Boolean masked,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo)
        throws FaultResponse
    ;

    /**
     * 
     * @param identity
     * @param tweak
     * @param format
     * @param authMethod
     * @param dataIn
     * @param authInfo
     * @return java.lang.String
     * @throws FaultResponse
     */
    @WebMethod(operationName = "ProtectFormattedData", action = "http://voltage.com/vibesimple/ProtectFormattedData")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "ProtectFormattedData", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectFormattedData")
    @ResponseWrapper(localName = "ProtectFormattedDataResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectFormattedDataResponse")
    public String protectFormattedData(
            @WebParam(name = "dataIn", targetNamespace = "")
            String dataIn,
            @WebParam(name = "format", targetNamespace = "")
            String format,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "tweak", targetNamespace = "")
            String tweak,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo)
        throws FaultResponse
    ;

    /**
     * 
     * @param identity
     * @param tweak
     * @param format
     * @param authMethod
     * @param dataIn
     * @param authInfo
     * @return java.lang.String
     * @throws FaultResponse
     */
    @WebMethod(operationName = "AccessFormattedData", action = "http://voltage.com/vibesimple/AccessFormattedData")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "AccessFormattedData", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessFormattedData")
    @ResponseWrapper(localName = "AccessFormattedDataResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessFormattedDataResponse")
    public String accessFormattedData(
            @WebParam(name = "dataIn", targetNamespace = "")
            String dataIn,
            @WebParam(name = "format", targetNamespace = "")
            String format,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "tweak", targetNamespace = "")
            String tweak,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo)
        throws FaultResponse
    ;

    /**
     * 
     * @param creditCardNumber
     * @param identity
     * @param tweak
     * @param authMethod
     * @param authInfo
     * @return java.util.List{@literal <}java.lang.String{@literal >}
     * @throws FaultResponse
     */
    @WebMethod(operationName = "ProtectCreditCardNumberList", action = "http://voltage.com/vibesimple/ProtectCreditCardNumberList")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "ProtectCreditCardNumberList", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectCreditCardNumberList")
    @ResponseWrapper(localName = "ProtectCreditCardNumberListResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectCreditCardNumberListResponse")
    public List<String> protectCreditCardNumberList(
            @WebParam(name = "creditCardNumber", targetNamespace = "")
            List<String> creditCardNumber,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "tweak", targetNamespace = "")
            String tweak,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo)
        throws FaultResponse
    ;

    /**
     * 
     * @param creditCardNumber
     * @param identity
     * @param tweak
     * @param masked
     * @param authMethod
     * @param authInfo
     * @return java.util.List{@literal <}java.lang.String{@literal >}
     * @throws FaultResponse
     */
    @WebMethod(operationName = "AccessCreditCardNumberList", action = "http://voltage.com/vibesimple/AccessCreditCardNumberList")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "AccessCreditCardNumberList", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessCreditCardNumberList")
    @ResponseWrapper(localName = "AccessCreditCardNumberListResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessCreditCardNumberListResponse")
    public List<String> accessCreditCardNumberList(
            @WebParam(name = "creditCardNumber", targetNamespace = "")
            List<String> creditCardNumber,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "tweak", targetNamespace = "")
            String tweak,
            @WebParam(name = "masked", targetNamespace = "")
            Boolean masked,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo)
        throws FaultResponse
    ;

    /**
     * 
     * @param socialSecurityNumber
     * @param identity
     * @param tweak
     * @param authMethod
     * @param authInfo
     * @return java.util.List{@literal <}java.lang.String{@literal >}
     * @throws FaultResponse
     */
    @WebMethod(operationName = "ProtectSocialSecurityNumberList", action = "http://voltage.com/vibesimple/ProtectSocialSecurityNumberList")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "ProtectSocialSecurityNumberList", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectSocialSecurityNumberList")
    @ResponseWrapper(localName = "ProtectSocialSecurityNumberListResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectSocialSecurityNumberListResponse")
    public List<String> protectSocialSecurityNumberList(
            @WebParam(name = "socialSecurityNumber", targetNamespace = "")
            List<String> socialSecurityNumber,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "tweak", targetNamespace = "")
            String tweak,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo)
        throws FaultResponse
    ;

    /**
     * 
     * @param socialSecurityNumber
     * @param identity
     * @param tweak
     * @param masked
     * @param authMethod
     * @param authInfo
     * @return java.util.List{@literal <}java.lang.String{@literal >}
     * @throws FaultResponse
     */
    @WebMethod(operationName = "AccessSocialSecurityNumberList", action = "http://voltage.com/vibesimple/AccessSocialSecurityNumberList")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "AccessSocialSecurityNumberList", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessSocialSecurityNumberList")
    @ResponseWrapper(localName = "AccessSocialSecurityNumberListResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessSocialSecurityNumberListResponse")
    public List<String> accessSocialSecurityNumberList(
            @WebParam(name = "socialSecurityNumber", targetNamespace = "")
            List<String> socialSecurityNumber,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "tweak", targetNamespace = "")
            String tweak,
            @WebParam(name = "masked", targetNamespace = "")
            Boolean masked,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo)
        throws FaultResponse
    ;

    /**
     * 
     * @param identity
     * @param tweak
     * @param format
     * @param authMethod
     * @param dataIn
     * @param authInfo
     * @return java.util.List{@literal <}java.lang.String{@literal >}
     * @throws FaultResponse
     */
    @WebMethod(operationName = "ProtectFormattedDataList", action = "http://voltage.com/vibesimple/ProtectFormattedDataList")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "ProtectFormattedDataList", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectFormattedDataList")
    @ResponseWrapper(localName = "ProtectFormattedDataListResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectFormattedDataListResponse")
    public List<String> protectFormattedDataList(
            @WebParam(name = "dataIn", targetNamespace = "")
            List<String> dataIn,
            @WebParam(name = "format", targetNamespace = "")
            String format,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "tweak", targetNamespace = "")
            String tweak,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo)
        throws FaultResponse
    ;

    /**
     * 
     * @param identity
     * @param tweak
     * @param format
     * @param authMethod
     * @param dataIn
     * @param authInfo
     * @return java.util.List{@literal <}java.lang.String{@literal >}
     * @throws FaultResponse
     */
    @WebMethod(operationName = "AccessFormattedDataList", action = "http://voltage.com/vibesimple/AccessFormattedDataList")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "AccessFormattedDataList", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessFormattedDataList")
    @ResponseWrapper(localName = "AccessFormattedDataListResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessFormattedDataListResponse")
    public List<String> accessFormattedDataList(
            @WebParam(name = "dataIn", targetNamespace = "")
            List<String> dataIn,
            @WebParam(name = "format", targetNamespace = "")
            String format,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "tweak", targetNamespace = "")
            String tweak,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo)
        throws FaultResponse
    ;

    /**
     * 
     * @param dataOut
     * @param creditCardNumber
     * @param identity
     * @param tweak
     * @param fullApplicationIdentityOut
     * @param authMethod
     * @param authInfo
     * @throws FaultResponse
     */
    @WebMethod(operationName = "ProtectCreditCardNumberV2", action = "http://voltage.com/vibesimple/ProtectCreditCardNumberV2")
    @RequestWrapper(localName = "ProtectCreditCardNumberV2", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectCreditCardNumberV2")
    @ResponseWrapper(localName = "ProtectCreditCardNumberV2Response", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectCreditCardNumberV2Response")
    public void protectCreditCardNumberV2(
            @WebParam(name = "creditCardNumber", targetNamespace = "")
            String creditCardNumber,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "tweak", targetNamespace = "")
            String tweak,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo,
            @WebParam(name = "dataOut", targetNamespace = "", mode = WebParam.Mode.OUT)
            Holder<String> dataOut,
            @WebParam(name = "fullApplicationIdentityOut", targetNamespace = "", mode = WebParam.Mode.OUT)
            Holder<String> fullApplicationIdentityOut)
        throws FaultResponse
    ;

    /**
     * 
     * @param dataOut
     * @param socialSecurityNumber
     * @param identity
     * @param tweak
     * @param fullApplicationIdentityOut
     * @param authMethod
     * @param authInfo
     * @throws FaultResponse
     */
    @WebMethod(operationName = "ProtectSocialSecurityNumberV2", action = "http://voltage.com/vibesimple/ProtectSocialSecurityNumberV2")
    @RequestWrapper(localName = "ProtectSocialSecurityNumberV2", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectSocialSecurityNumberV2")
    @ResponseWrapper(localName = "ProtectSocialSecurityNumberV2Response", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectSocialSecurityNumberV2Response")
    public void protectSocialSecurityNumberV2(
            @WebParam(name = "socialSecurityNumber", targetNamespace = "")
            String socialSecurityNumber,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "tweak", targetNamespace = "")
            String tweak,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo,
            @WebParam(name = "dataOut", targetNamespace = "", mode = WebParam.Mode.OUT)
            Holder<String> dataOut,
            @WebParam(name = "fullApplicationIdentityOut", targetNamespace = "", mode = WebParam.Mode.OUT)
            Holder<String> fullApplicationIdentityOut)
        throws FaultResponse
    ;

    /**
     * 
     * @param dataOut
     * @param identity
     * @param tweak
     * @param format
     * @param fullApplicationIdentityOut
     * @param authMethod
     * @param dataIn
     * @param authInfo
     * @throws FaultResponse
     */
    @WebMethod(operationName = "ProtectFormattedDataV2", action = "http://voltage.com/vibesimple/ProtectFormattedDataV2")
    @RequestWrapper(localName = "ProtectFormattedDataV2", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectFormattedDataV2")
    @ResponseWrapper(localName = "ProtectFormattedDataV2Response", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectFormattedDataV2Response")
    public void protectFormattedDataV2(
            @WebParam(name = "dataIn", targetNamespace = "")
            String dataIn,
            @WebParam(name = "format", targetNamespace = "")
            String format,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "tweak", targetNamespace = "")
            String tweak,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo,
            @WebParam(name = "dataOut", targetNamespace = "", mode = WebParam.Mode.OUT)
            Holder<String> dataOut,
            @WebParam(name = "fullApplicationIdentityOut", targetNamespace = "", mode = WebParam.Mode.OUT)
            Holder<String> fullApplicationIdentityOut)
        throws FaultResponse
    ;

    /**
     * 
     * @param dataOut
     * @param creditCardNumber
     * @param identity
     * @param tweak
     * @param fullApplicationIdentityOut
     * @param authMethod
     * @param authInfo
     * @throws FaultResponse
     */
    @WebMethod(operationName = "ProtectCreditCardNumberListV2", action = "http://voltage.com/vibesimple/ProtectCreditCardNumberListV2")
    @RequestWrapper(localName = "ProtectCreditCardNumberListV2", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectCreditCardNumberListV2")
    @ResponseWrapper(localName = "ProtectCreditCardNumberListV2Response", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectCreditCardNumberListV2Response")
    public void protectCreditCardNumberListV2(
            @WebParam(name = "creditCardNumber", targetNamespace = "")
            List<String> creditCardNumber,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "tweak", targetNamespace = "")
            String tweak,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo,
            @WebParam(name = "dataOut", targetNamespace = "", mode = WebParam.Mode.OUT)
            Holder<List<String>> dataOut,
            @WebParam(name = "fullApplicationIdentityOut", targetNamespace = "", mode = WebParam.Mode.OUT)
            Holder<String> fullApplicationIdentityOut)
        throws FaultResponse
    ;

    /**
     * 
     * @param dataOut
     * @param socialSecurityNumber
     * @param identity
     * @param tweak
     * @param fullApplicationIdentityOut
     * @param authMethod
     * @param authInfo
     * @throws FaultResponse
     */
    @WebMethod(operationName = "ProtectSocialSecurityNumberListV2", action = "http://voltage.com/vibesimple/ProtectSocialSecurityNumberListV2")
    @RequestWrapper(localName = "ProtectSocialSecurityNumberListV2", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectSocialSecurityNumberListV2")
    @ResponseWrapper(localName = "ProtectSocialSecurityNumberListV2Response", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectSocialSecurityNumberListV2Response")
    public void protectSocialSecurityNumberListV2(
            @WebParam(name = "socialSecurityNumber", targetNamespace = "")
            List<String> socialSecurityNumber,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "tweak", targetNamespace = "")
            String tweak,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo,
            @WebParam(name = "dataOut", targetNamespace = "", mode = WebParam.Mode.OUT)
            Holder<List<String>> dataOut,
            @WebParam(name = "fullApplicationIdentityOut", targetNamespace = "", mode = WebParam.Mode.OUT)
            Holder<String> fullApplicationIdentityOut)
        throws FaultResponse
    ;

    /**
     * 
     * @param dataOut
     * @param identity
     * @param tweak
     * @param format
     * @param fullApplicationIdentityOut
     * @param authMethod
     * @param dataIn
     * @param authInfo
     * @throws FaultResponse
     */
    @WebMethod(operationName = "ProtectFormattedDataListV2", action = "http://voltage.com/vibesimple/ProtectFormattedDataListV2")
    @RequestWrapper(localName = "ProtectFormattedDataListV2", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectFormattedDataListV2")
    @ResponseWrapper(localName = "ProtectFormattedDataListV2Response", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectFormattedDataListV2Response")
    public void protectFormattedDataListV2(
            @WebParam(name = "dataIn", targetNamespace = "")
            List<String> dataIn,
            @WebParam(name = "format", targetNamespace = "")
            String format,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "tweak", targetNamespace = "")
            String tweak,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo,
            @WebParam(name = "dataOut", targetNamespace = "", mode = WebParam.Mode.OUT)
            Holder<List<String>> dataOut,
            @WebParam(name = "fullApplicationIdentityOut", targetNamespace = "", mode = WebParam.Mode.OUT)
            Holder<String> fullApplicationIdentityOut)
        throws FaultResponse
    ;

    /**
     * 
     * @param identity
     * @param tweak
     * @param masked
     * @param format
     * @param authMethod
     * @param dataIn
     * @param authInfo
     * @return java.lang.String
     * @throws FaultResponse
     */
    @WebMethod(operationName = "AccessFormattedDataV2", action = "http://voltage.com/vibesimple/AccessFormattedDataV2")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "AccessFormattedDataV2", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessFormattedDataV2")
    @ResponseWrapper(localName = "AccessFormattedDataV2Response", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessFormattedDataV2Response")
    public String accessFormattedDataV2(
            @WebParam(name = "dataIn", targetNamespace = "")
            String dataIn,
            @WebParam(name = "format", targetNamespace = "")
            String format,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "tweak", targetNamespace = "")
            String tweak,
            @WebParam(name = "masked", targetNamespace = "")
            Boolean masked,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo)
        throws FaultResponse
    ;

    /**
     * 
     * @param identity
     * @param tweak
     * @param masked
     * @param format
     * @param authMethod
     * @param dataIn
     * @param authInfo
     * @return java.util.List{@literal <}java.lang.String{@literal >}
     * @throws FaultResponse
     */
    @WebMethod(operationName = "AccessFormattedDataListV2", action = "http://voltage.com/vibesimple/AccessFormattedDataListV2")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "AccessFormattedDataListV2", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessFormattedDataListV2")
    @ResponseWrapper(localName = "AccessFormattedDataListV2Response", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessFormattedDataListV2Response")
    public List<String> accessFormattedDataListV2(
            @WebParam(name = "dataIn", targetNamespace = "")
            List<String> dataIn,
            @WebParam(name = "format", targetNamespace = "")
            String format,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "tweak", targetNamespace = "")
            String tweak,
            @WebParam(name = "masked", targetNamespace = "")
            Boolean masked,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo)
        throws FaultResponse
    ;

    /**
     * 
     * @param identity
     * @param generateTweak
     * @param authMethod
     * @param dataIn
     * @param authInfo
     * @param algorithm
     * @return byte[]
     * @throws FaultResponse
     */
    @WebMethod(operationName = "ProtectGenericData", action = "http://voltage.com/vibesimple/ProtectGenericData")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "ProtectGenericData", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectGenericData")
    @ResponseWrapper(localName = "ProtectGenericDataResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectGenericDataResponse")
    public byte[] protectGenericData(
            @WebParam(name = "dataIn", targetNamespace = "")
            byte[] dataIn,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "generateTweak", targetNamespace = "")
            Boolean generateTweak,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo,
            @WebParam(name = "algorithm", targetNamespace = "")
            String algorithm)
        throws FaultResponse
    ;

    /**
     * 
     * @param identity
     * @param masked
     * @param maskingFormat
     * @param authMethod
     * @param dataIn
     * @param authInfo
     * @return byte[]
     * @throws FaultResponse
     */
    @WebMethod(operationName = "AccessGenericData", action = "http://voltage.com/vibesimple/AccessGenericData")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "AccessGenericData", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessGenericData")
    @ResponseWrapper(localName = "AccessGenericDataResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessGenericDataResponse")
    public byte[] accessGenericData(
            @WebParam(name = "dataIn", targetNamespace = "")
            byte[] dataIn,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "maskingFormat", targetNamespace = "")
            String maskingFormat,
            @WebParam(name = "masked", targetNamespace = "")
            Boolean masked,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo)
        throws FaultResponse
    ;

    /**
     * 
     * @param dataIn
     * @return java.lang.String
     * @throws FaultResponse
     */
    @WebMethod(operationName = "GetGenericDataIdentity", action = "http://voltage.com/vibesimple/GetGenericDataIdentity")
    @WebResult(name = "identity", targetNamespace = "")
    @RequestWrapper(localName = "GetGenericDataIdentity", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.GetGenericDataIdentity")
    @ResponseWrapper(localName = "GetGenericDataIdentityResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.GetGenericDataIdentityResponse")
    public String getGenericDataIdentity(
            @WebParam(name = "dataIn", targetNamespace = "")
            byte[] dataIn)
        throws FaultResponse
    ;

    /**
     * 
     * @param identity
     * @param generateTweak
     * @param authMethod
     * @param dataIn
     * @param authInfo
     * @param algorithm
     * @return java.lang.String
     * @throws FaultResponse
     */
    @WebMethod(operationName = "ProtectGenericStringData", action = "http://voltage.com/vibesimple/ProtectGenericStringData")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "ProtectGenericStringData", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectGenericStringData")
    @ResponseWrapper(localName = "ProtectGenericStringDataResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectGenericStringDataResponse")
    public String protectGenericStringData(
            @WebParam(name = "dataIn", targetNamespace = "")
            String dataIn,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "generateTweak", targetNamespace = "")
            Boolean generateTweak,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo,
            @WebParam(name = "algorithm", targetNamespace = "")
            String algorithm)
        throws FaultResponse
    ;

    /**
     * 
     * @param identity
     * @param masked
     * @param maskingFormat
     * @param authMethod
     * @param dataIn
     * @param authInfo
     * @return java.lang.String
     * @throws FaultResponse
     */
    @WebMethod(operationName = "AccessGenericStringData", action = "http://voltage.com/vibesimple/AccessGenericStringData")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "AccessGenericStringData", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessGenericStringData")
    @ResponseWrapper(localName = "AccessGenericStringDataResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessGenericStringDataResponse")
    public String accessGenericStringData(
            @WebParam(name = "dataIn", targetNamespace = "")
            String dataIn,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "maskingFormat", targetNamespace = "")
            String maskingFormat,
            @WebParam(name = "masked", targetNamespace = "")
            Boolean masked,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo)
        throws FaultResponse
    ;

    /**
     * 
     * @param dataIn
     * @return java.lang.String
     * @throws FaultResponse
     */
    @WebMethod(operationName = "GetGenericStringDataIdentity", action = "http://voltage.com/vibesimple/GetGenericStringDataIdentity")
    @WebResult(name = "identity", targetNamespace = "")
    @RequestWrapper(localName = "GetGenericStringDataIdentity", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.GetGenericStringDataIdentity")
    @ResponseWrapper(localName = "GetGenericStringDataIdentityResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.GetGenericStringDataIdentityResponse")
    public String getGenericStringDataIdentity(
            @WebParam(name = "dataIn", targetNamespace = "")
            String dataIn)
        throws FaultResponse
    ;

    /**
     * 
     * @param identity
     * @param generateTweak
     * @param authMethod
     * @param dataIn
     * @param authInfo
     * @param algorithm
     * @return java.util.List{@literal <}byte[]{@literal > }
     * @throws FaultResponse
     */
    @WebMethod(operationName = "ProtectGenericDataList", action = "http://voltage.com/vibesimple/ProtectGenericDataList")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "ProtectGenericDataList", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectGenericDataList")
    @ResponseWrapper(localName = "ProtectGenericDataListResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectGenericDataListResponse")
    public List<byte[]> protectGenericDataList(
            @WebParam(name = "dataIn", targetNamespace = "")
            List<byte[]> dataIn,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "generateTweak", targetNamespace = "")
            Boolean generateTweak,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo,
            @WebParam(name = "algorithm", targetNamespace = "")
            String algorithm)
        throws FaultResponse
    ;

    /**
     * 
     * @param identity
     * @param masked
     * @param maskingFormat
     * @param authMethod
     * @param dataIn
     * @param authInfo
     * @return java.util.List{@literal <}byte[]{@literal >}
     * @throws FaultResponse
     */
    @WebMethod(operationName = "AccessGenericDataList", action = "http://voltage.com/vibesimple/AccessGenericDataList")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "AccessGenericDataList", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessGenericDataList")
    @ResponseWrapper(localName = "AccessGenericDataListResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessGenericDataListResponse")
    public List<byte[]> accessGenericDataList(
            @WebParam(name = "dataIn", targetNamespace = "")
            List<byte[]> dataIn,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "maskingFormat", targetNamespace = "")
            String maskingFormat,
            @WebParam(name = "masked", targetNamespace = "")
            Boolean masked,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo)
        throws FaultResponse
    ;

    /**
     * 
     * @param dataIn
     * @return java.util.List{@literal <}java.lang.String{@literal >}
     * @throws FaultResponse
     */
    @WebMethod(operationName = "GetGenericDataIdentityList", action = "http://voltage.com/vibesimple/GetGenericDataIdentityList")
    @WebResult(name = "identity", targetNamespace = "")
    @RequestWrapper(localName = "GetGenericDataIdentityList", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.GetGenericDataIdentityList")
    @ResponseWrapper(localName = "GetGenericDataIdentityListResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.GetGenericDataIdentityListResponse")
    public List<String> getGenericDataIdentityList(
            @WebParam(name = "dataIn", targetNamespace = "")
            List<byte[]> dataIn)
        throws FaultResponse
    ;

    /**
     * 
     * @param identity
     * @param generateTweak
     * @param authMethod
     * @param dataIn
     * @param authInfo
     * @param algorithm
     * @return java.util.List{@literal <}java.lang.String{@literal >}
     * @throws FaultResponse
     */
    @WebMethod(operationName = "ProtectGenericStringDataList", action = "http://voltage.com/vibesimple/ProtectGenericStringDataList")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "ProtectGenericStringDataList", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectGenericStringDataList")
    @ResponseWrapper(localName = "ProtectGenericStringDataListResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectGenericStringDataListResponse")
    public List<String> protectGenericStringDataList(
            @WebParam(name = "dataIn", targetNamespace = "")
            List<String> dataIn,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "generateTweak", targetNamespace = "")
            Boolean generateTweak,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo,
            @WebParam(name = "algorithm", targetNamespace = "")
            String algorithm)
        throws FaultResponse
    ;

    /**
     * 
     * @param identity
     * @param masked
     * @param maskingFormat
     * @param authMethod
     * @param dataIn
     * @param authInfo
     * @return
     *     returns java.util.List{@literal <}java.lang.String{@literal >}
     * @throws FaultResponse
     */
    @WebMethod(operationName = "AccessGenericStringDataList", action = "http://voltage.com/vibesimple/AccessGenericStringDataList")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "AccessGenericStringDataList", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessGenericStringDataList")
    @ResponseWrapper(localName = "AccessGenericStringDataListResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessGenericStringDataListResponse")
    public List<String> accessGenericStringDataList(
            @WebParam(name = "dataIn", targetNamespace = "")
            List<String> dataIn,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "maskingFormat", targetNamespace = "")
            String maskingFormat,
            @WebParam(name = "masked", targetNamespace = "")
            Boolean masked,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo)
        throws FaultResponse
    ;

    /**
     * 
     * @param dataIn
     * @return java.util.List{@literal <}java.lang.String{@literal >}
     * @throws FaultResponse
     */
    @WebMethod(operationName = "GetGenericStringDataIdentityList", action = "http://voltage.com/vibesimple/GetGenericStringDataIdentityList")
    @WebResult(name = "identity", targetNamespace = "")
    @RequestWrapper(localName = "GetGenericStringDataIdentityList", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.GetGenericStringDataIdentityList")
    @ResponseWrapper(localName = "GetGenericStringDataIdentityListResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.GetGenericStringDataIdentityListResponse")
    public List<String> getGenericStringDataIdentityList(
            @WebParam(name = "dataIn", targetNamespace = "")
            List<String> dataIn)
        throws FaultResponse
    ;

    /**
     * 
     * @param identity
     * @param tweak
     * @param format
     * @param authMethod
     * @param dataIn
     * @param authInfo
     * @return java.util.List{@literal <}java.lang.String{@literal >}
     * @throws FaultResponse
     */
    @WebMethod(operationName = "ProtectFormattedDataWithAllKeyNumbers", action = "http://voltage.com/vibesimple/ProtectFormattedDataWithAllKeyNumbers")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "ProtectFormattedDataWithAllKeyNumbers", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectFormattedDataWithAllKeyNumbers")
    @ResponseWrapper(localName = "ProtectFormattedDataWithAllKeyNumbersResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectFormattedDataWithAllKeyNumbersResponse")
    public List<String> protectFormattedDataWithAllKeyNumbers(
            @WebParam(name = "dataIn", targetNamespace = "")
            String dataIn,
            @WebParam(name = "format", targetNamespace = "")
            String format,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "tweak", targetNamespace = "")
            String tweak,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo)
        throws FaultResponse
    ;

    /**
     * 
     * @param secondaryNamespace
     * @param primaryNamespace
     * @param identity
     * @param tweak
     * @param format
     * @param authMethod
     * @param dataIn
     * @param authInfo
     * @return
     *     returns java.lang.String
     * @throws FaultResponse
     */
    @WebMethod(operationName = "ProtectFormattedDataMultiplexed", action = "http://voltage.com/vibesimple/ProtectFormattedDataMultiplexed")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "ProtectFormattedDataMultiplexed", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectFormattedDataMultiplexed")
    @ResponseWrapper(localName = "ProtectFormattedDataMultiplexedResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectFormattedDataMultiplexedResponse")
    public String protectFormattedDataMultiplexed(
            @WebParam(name = "dataIn", targetNamespace = "")
            String dataIn,
            @WebParam(name = "format", targetNamespace = "")
            String format,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "tweak", targetNamespace = "")
            String tweak,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo,
            @WebParam(name = "primaryNamespace", targetNamespace = "")
            String primaryNamespace,
            @WebParam(name = "secondaryNamespace", targetNamespace = "")
            String secondaryNamespace)
        throws FaultResponse
    ;

    /**
     * 
     * @param secondaryNamespace
     * @param primaryNamespace
     * @param identity
     * @param tweak
     * @param format
     * @param authMethod
     * @param dataIn
     * @param authInfo
     * @return java.util.List{@literal <}java.lang.String{@literal >}
     * @throws FaultResponse
     */
    @WebMethod(operationName = "ProtectFormattedDataListMultiplexed", action = "http://voltage.com/vibesimple/ProtectFormattedDataListMultiplexed")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "ProtectFormattedDataListMultiplexed", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectFormattedDataListMultiplexed")
    @ResponseWrapper(localName = "ProtectFormattedDataListMultiplexedResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectFormattedDataListMultiplexedResponse")
    public List<String> protectFormattedDataListMultiplexed(
            @WebParam(name = "dataIn", targetNamespace = "")
            List<String> dataIn,
            @WebParam(name = "format", targetNamespace = "")
            String format,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "tweak", targetNamespace = "")
            String tweak,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo,
            @WebParam(name = "primaryNamespace", targetNamespace = "")
            String primaryNamespace,
            @WebParam(name = "secondaryNamespace", targetNamespace = "")
            String secondaryNamespace)
        throws FaultResponse
    ;

    /**
     * 
     * @param secondaryNamespace
     * @param primaryNamespace
     * @param identity
     * @param tweak
     * @param format
     * @param authMethod
     * @param dataIn
     * @param authInfo
     * @return java.lang.String
     * @throws FaultResponse
     */
    @WebMethod(operationName = "AccessFormattedDataMultiplexed", action = "http://voltage.com/vibesimple/AccessFormattedDataMultiplexed")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "AccessFormattedDataMultiplexed", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessFormattedDataMultiplexed")
    @ResponseWrapper(localName = "AccessFormattedDataMultiplexedResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessFormattedDataMultiplexedResponse")
    public String accessFormattedDataMultiplexed(
            @WebParam(name = "dataIn", targetNamespace = "")
            String dataIn,
            @WebParam(name = "format", targetNamespace = "")
            String format,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "tweak", targetNamespace = "")
            String tweak,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo,
            @WebParam(name = "primaryNamespace", targetNamespace = "")
            String primaryNamespace,
            @WebParam(name = "secondaryNamespace", targetNamespace = "")
            String secondaryNamespace)
        throws FaultResponse
    ;

    /**
     * 
     * @param secondaryNamespace
     * @param primaryNamespace
     * @param identity
     * @param tweak
     * @param format
     * @param authMethod
     * @param dataIn
     * @param authInfo
     * @return java.util.List{@literal <}java.lang.String{@literal >}
     * @throws FaultResponse
     */
    @WebMethod(operationName = "AccessFormattedDataListMultiplexed", action = "http://voltage.com/vibesimple/AccessFormattedDataListMultiplexed")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "AccessFormattedDataListMultiplexed", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessFormattedDataListMultiplexed")
    @ResponseWrapper(localName = "AccessFormattedDataListMultiplexedResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessFormattedDataListMultiplexedResponse")
    public List<String> accessFormattedDataListMultiplexed(
            @WebParam(name = "dataIn", targetNamespace = "")
            List<String> dataIn,
            @WebParam(name = "format", targetNamespace = "")
            String format,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "tweak", targetNamespace = "")
            String tweak,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo,
            @WebParam(name = "primaryNamespace", targetNamespace = "")
            String primaryNamespace,
            @WebParam(name = "secondaryNamespace", targetNamespace = "")
            String secondaryNamespace)
        throws FaultResponse
    ;

    /**
     * 
     * @param secondaryNamespace
     * @param primaryNamespace
     * @param identity
     * @param tweak
     * @param masked
     * @param format
     * @param authMethod
     * @param dataIn
     * @param authInfo
     * @return java.lang.String
     * @throws FaultResponse
     */
    @WebMethod(operationName = "AccessFormattedDataMultiplexedV2", action = "http://voltage.com/vibesimple/AccessFormattedDataMultiplexedV2")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "AccessFormattedDataMultiplexedV2", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessFormattedDataMultiplexedV2")
    @ResponseWrapper(localName = "AccessFormattedDataMultiplexedV2Response", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessFormattedDataMultiplexedV2Response")
    public String accessFormattedDataMultiplexedV2(
            @WebParam(name = "dataIn", targetNamespace = "")
            String dataIn,
            @WebParam(name = "format", targetNamespace = "")
            String format,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "tweak", targetNamespace = "")
            String tweak,
            @WebParam(name = "masked", targetNamespace = "")
            boolean masked,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo,
            @WebParam(name = "primaryNamespace", targetNamespace = "")
            String primaryNamespace,
            @WebParam(name = "secondaryNamespace", targetNamespace = "")
            String secondaryNamespace)
        throws FaultResponse
    ;

    /**
     * 
     * @param secondaryNamespace
     * @param primaryNamespace
     * @param identity
     * @param tweak
     * @param masked
     * @param format
     * @param authMethod
     * @param dataIn
     * @param authInfo
     * @return java.util.List{@literal <}java.lang.String{@literal >}
     * @throws FaultResponse
     */
    @WebMethod(operationName = "AccessFormattedDataListMultiplexedV2", action = "http://voltage.com/vibesimple/AccessFormattedDataListMultiplexedV2")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "AccessFormattedDataListMultiplexedV2", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessFormattedDataListMultiplexedV2")
    @ResponseWrapper(localName = "AccessFormattedDataListMultiplexedV2Response", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessFormattedDataListMultiplexedV2Response")
    public List<String> accessFormattedDataListMultiplexedV2(
            @WebParam(name = "dataIn", targetNamespace = "")
            List<String> dataIn,
            @WebParam(name = "format", targetNamespace = "")
            String format,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "tweak", targetNamespace = "")
            String tweak,
            @WebParam(name = "masked", targetNamespace = "")
            boolean masked,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo,
            @WebParam(name = "primaryNamespace", targetNamespace = "")
            String primaryNamespace,
            @WebParam(name = "secondaryNamespace", targetNamespace = "")
            String secondaryNamespace)
        throws FaultResponse
    ;

    /**
     * 
     * @param dataIn
     * @return java.lang.String
     * @throws FaultResponse
     */
    @WebMethod(operationName = "EchoData", action = "http://voltage.com/vibesimple/EchoData")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "EchoData", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.EchoData")
    @ResponseWrapper(localName = "EchoDataResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.EchoDataResponse")
    public String echoData(
            @WebParam(name = "dataIn", targetNamespace = "")
            String dataIn)
        throws FaultResponse
    ;

    /**
     * 
     * @param dataIn
     * @return java.util.List{@literal <}java.lang.String{@literal >}
     * @throws FaultResponse
     */
    @WebMethod(operationName = "EchoDataList", action = "http://voltage.com/vibesimple/EchoDataList")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "EchoDataList", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.EchoDataList")
    @ResponseWrapper(localName = "EchoDataListResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.EchoDataListResponse")
    public List<String> echoDataList(
            @WebParam(name = "dataIn", targetNamespace = "")
            List<String> dataIn)
        throws FaultResponse
    ;

    /**
     * 
     * @param identity
     * @param tweak
     * @param format
     * @param authMethod
     * @param dataIn
     * @param authInfo
     * @return java.util.List{@literal <}com.kunai.keyvault.crypto.voltage.vibesimple.DataRange{@literal >}
     * @throws FaultResponse
     */
    @WebMethod(operationName = "ProtectFormattedDataRangeList", action = "http://voltage.com/vibesimple/ProtectFormattedDataRangeList")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "ProtectFormattedDataRangeList", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectFormattedDataRangeList")
    @ResponseWrapper(localName = "ProtectFormattedDataRangeListResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.ProtectFormattedDataRangeListResponse")
    public List<DataRange> protectFormattedDataRangeList(
            @WebParam(name = "dataIn", targetNamespace = "")
            List<DataRange> dataIn,
            @WebParam(name = "format", targetNamespace = "")
            String format,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "tweak", targetNamespace = "")
            String tweak,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo)
        throws FaultResponse
    ;

    /**
     * 
     * @param identity
     * @param tweak
     * @param format
     * @param authMethod
     * @param dataIn
     * @param authInfo
     * @return java.util.List{@literal <}com.kunai.keyvault.crypto.voltage.vibesimple.DataRange{@literal >}
     * @throws FaultResponse
     */
    @WebMethod(operationName = "AccessFormattedDataRangeList", action = "http://voltage.com/vibesimple/AccessFormattedDataRangeList")
    @WebResult(name = "dataOut", targetNamespace = "")
    @RequestWrapper(localName = "AccessFormattedDataRangeList", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessFormattedDataRangeList")
    @ResponseWrapper(localName = "AccessFormattedDataRangeListResponse", targetNamespace = "http://voltage.com/vibesimple", className = "com.kunai.keyvault.crypto.voltage.vibesimple.AccessFormattedDataRangeListResponse")
    public List<DataRange> accessFormattedDataRangeList(
            @WebParam(name = "dataIn", targetNamespace = "")
            List<DataRange> dataIn,
            @WebParam(name = "format", targetNamespace = "")
            String format,
            @WebParam(name = "identity", targetNamespace = "")
            String identity,
            @WebParam(name = "tweak", targetNamespace = "")
            String tweak,
            @WebParam(name = "authMethod", targetNamespace = "")
            AuthMethod authMethod,
            @WebParam(name = "authInfo", targetNamespace = "")
            String authInfo)
        throws FaultResponse
    ;

}
