
package com.kunai.keyvault.crypto.voltage.vibesimple;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Fault", targetNamespace = "http://voltage.com/vibesimple")
public class FaultResponse
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private Fault faultInfo;

    /**
     * 
     * @param faultInfo information about the error/fault.
     * @param message a description that throws the error.
     */
    public FaultResponse(String message, Fault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo information about the error/fault.
     * @param cause a Throwable object that gives the cause from the Stacktrace.
     * @param message a description that throws the error.
     */
    public FaultResponse(String message, Fault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.kunai.keyvault.crypto.voltage.vibesimple.Fault
     */
    public Fault getFaultInfo() {
        return faultInfo;
    }

}
